version: "3.4"

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 65258:443
      - 65257:80
    expose:
      - 443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - postgres
    networks:
      - postgres
      - dotnet

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresweb}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - dotnet

networks:
  postgres:
    driver: bridge
  dotnet:
    driver: bridge
